
# -*- coding: utf-8 -*-

# This Server Code is Automatically Generated By 
# DocAPI Python Utility.
# Date: 2020 31 Jul, 05:36 AM
# Github: https://github.com/sabbiramin113008/docapi


from flask import Flask, jsonify, request

app = Flask(__name__)
app.secret_key = 'SomeSecretKey'


@app.route('/api/books/id', method=['GET','POST'])
def get_book_by_id():
    if request.method in ['GET','POST']:
        response = {'flag': 1, 'response': 'kl'}
        return jsonify(response), 300

if __name__=='__main__':
    app.run(
        host='localhost',
        port=1034,
        debug=True
    )
